apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-container
        image: us-east1-docker.pkg.dev/molten-unison-401314/images/vue-gke:latest
        ports:
        - containerPort: 80