name: Deploy to Artifact Registry

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.8.0
        with:
          version: '333.0.0'

      - name: Configure Docker credentials for Google Artifact Registry
        run: |
          gcloud auth configure-docker gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/$GOOGLE_PROJECT_ID/$GCR_REPOSITORY:latest .
          docker push gcr.io/$GOOGLE_PROJECT_ID/$GCR_REPOSITORY:latest
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
          GCR_REPOSITORY: vue-app-gke
